import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const neue = localFont({
  src: "./fonts/NeueMontreal-Regular.ttf",
  display: "swap",
  variable: "--font-neue",
});

export const metadata: Metadata = {
  title: "AnimatedWeb",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={neue.variable}>
      <body>{children}</body>
    </html>
  );
}
