import type { Metadata } from "next";
import { Inter } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
const neue = localFont({
  src: "./fonts/NeueMontreal-Regular.ttf",
  display: "swap",
  variable: "--font-neue",
});

const grotesk = localFont({
  src: "./fonts/FoundersGrotesk-Semibold.ttf",
  display: "swap",
  variable: "--font-grotesk",
});

export const metadata: Metadata = {
  title: "AnimatedWeb",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${neue.variable} ${grotesk.variable}`}>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
